# Form implementation generated from reading ui file 'ui_forms/CreateRequest.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(603, 649)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 557, 601))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label = QtWidgets.QLabel(parent=self.widget)
        self.logo_label.setMinimumSize(QtCore.QSize(100, 100))
        self.logo_label.setMaximumSize(QtCore.QSize(100, 100))
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout.addWidget(self.logo_label)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("font: 18pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("font: 10pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.product_tableView = QtWidgets.QTableView(parent=self.widget)
        self.product_tableView.setMinimumSize(QtCore.QSize(411, 201))
        self.product_tableView.setStyleSheet("background-color: rgb(187, 220, 250);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.product_tableView.setObjectName("product_tableView")
        self.verticalLayout.addWidget(self.product_tableView)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setStyleSheet("font: 10pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setStyleSheet("background-color: rgb(187, 220, 250);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.add_pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.add_pushButton_3.setMinimumSize(QtCore.QSize(131, 24))
        self.add_pushButton_3.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.add_pushButton_3.setObjectName("add_pushButton_3")
        self.verticalLayout_3.addWidget(self.add_pushButton_3)
        self.del_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.del_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.del_pushButton.setObjectName("del_pushButton")
        self.verticalLayout_3.addWidget(self.del_pushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setStyleSheet("font: 10pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.sostav_tableView = QtWidgets.QTableView(parent=self.widget)
        self.sostav_tableView.setMinimumSize(QtCore.QSize(411, 201))
        self.sostav_tableView.setStyleSheet("background-color: rgb(187, 220, 250);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.sostav_tableView.setObjectName("sostav_tableView")
        self.verticalLayout_2.addWidget(self.sostav_tableView)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exit_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(121, 31))
        self.exit_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.horizontalLayout_2.addWidget(self.exit_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.save_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.save_pushButton.setMinimumSize(QtCore.QSize(121, 31))
        self.save_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout_2.addWidget(self.save_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создание заявки"))
        self.label_3.setText(_translate("Dialog", "\"Новые технологии\""))
        self.label.setText(_translate("Dialog", "Продукты"))
        self.label_2.setText(_translate("Dialog", "Количество"))
        self.add_pushButton_3.setText(_translate("Dialog", "Добавить продукт"))
        self.del_pushButton.setText(_translate("Dialog", "Удалить продукт"))
        self.label_4.setText(_translate("Dialog", "Состав заявки"))
        self.exit_pushButton.setText(_translate("Dialog", "Отмена"))
        self.save_pushButton.setText(_translate("Dialog", "Сохранить заявку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
