# Form implementation generated from reading ui file 'ui_forms/Partners.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(542, 338)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 501, 291))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("font: 10pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.partners_tableView = QtWidgets.QTableView(parent=self.widget)
        self.partners_tableView.setMinimumSize(QtCore.QSize(411, 201))
        self.partners_tableView.setStyleSheet("background-color: rgb(187, 220, 250);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.partners_tableView.setObjectName("partners_tableView")
        self.verticalLayout.addWidget(self.partners_tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exit_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(121, 31))
        self.exit_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.horizontalLayout.addWidget(self.exit_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.save_pushButton.setMinimumSize(QtCore.QSize(121, 31))
        self.save_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout.addWidget(self.save_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Сохранение заявки"))
        self.label.setText(_translate("Dialog", "Партнеры"))
        self.exit_pushButton.setText(_translate("Dialog", "Отмена"))
        self.save_pushButton.setText(_translate("Dialog", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
