# Form implementation generated from reading ui file 'ui_forms/Request.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 414)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 583, 399))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label = QtWidgets.QLabel(parent=self.widget)
        self.logo_label.setMinimumSize(QtCore.QSize(100, 100))
        self.logo_label.setMaximumSize(QtCore.QSize(100, 100))
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout.addWidget(self.logo_label)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("font: 18pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("font: 10pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.update_pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.update_pushButton_2.setMinimumSize(QtCore.QSize(101, 31))
        self.update_pushButton_2.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.update_pushButton_2.setObjectName("update_pushButton_2")
        self.verticalLayout.addWidget(self.update_pushButton_2)
        self.tableView = QtWidgets.QTableView(parent=self.widget)
        self.tableView.setMinimumSize(QtCore.QSize(579, 192))
        self.tableView.setStyleSheet("background-color: rgb(187, 220, 250);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.add_pushButton.setMinimumSize(QtCore.QSize(101, 31))
        self.add_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout_2.addWidget(self.add_pushButton)
        self.change_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.change_pushButton.setMinimumSize(QtCore.QSize(101, 31))
        self.change_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.change_pushButton.setObjectName("change_pushButton")
        self.horizontalLayout_2.addWidget(self.change_pushButton)
        self.sostav_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.sostav_pushButton.setMinimumSize(QtCore.QSize(101, 31))
        self.sostav_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.sostav_pushButton.setObjectName("sostav_pushButton")
        self.horizontalLayout_2.addWidget(self.sostav_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заявки"))
        self.label_3.setText(_translate("MainWindow", "\"Новые технологии\""))
        self.label.setText(_translate("MainWindow", "Заявки"))
        self.update_pushButton_2.setText(_translate("MainWindow", "Обновить заявки"))
        self.add_pushButton.setText(_translate("MainWindow", "Добавить заявку"))
        self.change_pushButton.setText(_translate("MainWindow", "Редактировать"))
        self.sostav_pushButton.setText(_translate("MainWindow", "Состав заявки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
