# Form implementation generated from reading ui file 'ui_forms/SostavRequest.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 447)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 20, 561, 391))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label = QtWidgets.QLabel(parent=self.widget)
        self.logo_label.setMinimumSize(QtCore.QSize(100, 100))
        self.logo_label.setMaximumSize(QtCore.QSize(100, 100))
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout.addWidget(self.logo_label)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("font: 18pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("font: 10pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sostav_tableView = QtWidgets.QTableView(parent=self.widget)
        self.sostav_tableView.setMinimumSize(QtCore.QSize(471, 201))
        self.sostav_tableView.setStyleSheet("background-color: rgb(187, 220, 250);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.sostav_tableView.setObjectName("sostav_tableView")
        self.verticalLayout.addWidget(self.sostav_tableView)
        self.exit_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(121, 31))
        self.exit_pushButton.setStyleSheet("background-color: rgb(12, 72, 130);\n"
"font: 9pt \"Bahnschrift\";\n"
"color: rgb(0, 0, 0);")
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.verticalLayout.addWidget(self.exit_pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Состав заявки"))
        self.label_3.setText(_translate("Dialog", "\"Новые технологии\""))
        self.label.setText(_translate("Dialog", "Состав"))
        self.exit_pushButton.setText(_translate("Dialog", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
